name: Docker Image

on:
  workflow_dispatch:
  push:
    tags:
      - '*'
      
jobs:
  push_to_registry:
    name: Push docker image to hub
    runs-on: ubuntu-latest
    steps:
      - name: check repository
        uses: actions/checkout@v4
      - name: GitHub Tag Name example
        run: |
          echo "Tag name from github.ref_name: ${{  github.ref_name }}"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: login to docker registry
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      - name: build and push docker image to registry
        uses: docker/build-push-action@v6
        with:
          push: true
          platforms: ${{ vars.DOCKER_PLATFORMS }}
          build-args: |
            BUILD_FROM=python:${{ vars.PYTHON_VERSION }}-alpine
            DOCKER_TAG=${{github.ref_name}}
          tags: "${{ vars.DOCKER_HUB_REPOSITORY }}:latest,${{ vars.DOCKER_HUB_REPOSITORY }}:${{github.ref_name}}"
